apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kgcentral

resources:
  - ../../base

replicas:
  - name: frontend
    count: 2
  - name: backend
    count: 2
  - name: ai-service
    count: 1

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: kgcentral/backend:latest
    target:
      kind: Deployment
      name: backend
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: kgcentral/frontend:latest
    target:
      kind: Deployment
      name: frontend
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: kgcentral/ai-service:latest
    target:
      kind: Deployment
      name: ai-service
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env
        value:
          - name: NODE_ENV
            value: "production"
          - name: PORT
            value: "4000"
          - name: LOG_LEVEL
            value: "warn"
    target:
      kind: Deployment
      name: backend

commonLabels:
  env: production
